# Encode target labels with value between 0 and n_classes-1.

# This transformer should be used to encode target values, i.e. y, and not the input X.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/income_evaluation.csv')
df.head()

age          workclass   fnlwgt   education   education-num  \
0   39          State-gov    77516   Bachelors              13   
1   50   Self-emp-not-inc    83311   Bachelors              13   
2   38            Private   215646     HS-grad               9   
3   53            Private   234721        11th               7   
4   28            Private   338409   Bachelors              13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

    capital-gain   capital-loss   hours-per-week  native-country  income  
0           2174              0               40   United-States   <=50K  
1              0              0               13   United-States   <=50K  
2              0              0               40   United-States   <=50K  
3              0              0               40   United-States   <=50K  
4              0              0               40            Cuba   <=50K

In [3]:
df.columns

Index(['age', ' workclass', ' fnlwgt', ' education', ' education-num',
       ' marital-status', ' occupation', ' relationship', ' race', ' sex',
       ' capital-gain', ' capital-loss', ' hours-per-week', ' native-country',
       ' income'],
      dtype='object')

In [4]:
df[' income'].value_counts()

 <=50K    24720
 >50K      7841
Name:  income, dtype: int64

# Let's split data

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(' income', axis=1), df[' income'],
                                                   test_size=0.2, random_state=0)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
le.fit(y_train)

LabelEncoder()

In [11]:
#check classes
le.classes_

array([' <=50K', ' >50K'], dtype=object)

In [15]:
#transform for y_train
le.transform(y_train)

array([0, 0, 0, ..., 0, 1, 0])

In [14]:
#check it in form of data frames
pd.Series(le.transform(y_train))

0        0
1        0
2        0
3        0
4        0
        ..
26043    1
26044    0
26045    0
26046    1
26047    0
Length: 26048, dtype: int64

In [17]:
#transform for y test
le.transform(y_test)

array([0, 0, 0, ..., 1, 0, 1])

# Since label encoder uses 0 or 1 for category therefore it is only recommended for y_train & y_test

# it will mark an error if chosen on X_train,X_test for e.g.

In [24]:
X_train[' native-country']

15282     United-States
24870     United-States
18822     United-States
26404     United-States
7842      United-States
              ...      
13123     United-States
19648     United-States
9845      United-States
10799     United-States
2732      United-States
Name:  native-country, Length: 26048, dtype: object

In [18]:
#let's try it on native country
le1 = LabelEncoder()

In [22]:
le1.fit(X_train[' native-country'])

LabelEncoder()

In [23]:
le1.transform(X_train[' native-country'])

array([39, 39, 39, ..., 39, 39, 39])

In [25]:
pd.Series(le1.transform(X_train[' native-country']))

0        39
1        39
2        39
3        39
4        39
         ..
26043    39
26044    39
26045    39
26046    39
26047    39
Length: 26048, dtype: int64

Now if we feed these to our machine learning model, it will think no. in acsending order with preferences
These are just nominal categorical variable not an ordinal one